name: module3_task0

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Executes once per day

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate Makefile
        run: |
          make help
