---
name: module3_task1

on:   #add
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install markdownlint
        run: sudo apt-get update && sudo apt-get install -y markdownlint

      - name: Run bash script
        run: cd module3_task1 && ./setup.sh

      - name: Run make build
        run: |
          cd module3_task1
          make build
